name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Clojure
      run: curl -O https://download.clojure.org/install/linux-install-1.11.1.1257.sh
    - name: Chmod
      run: chmod +x linux-install-1.11.1.1257.sh
    - name: Install
      run: ./linux-install-1.11.1.1257.sh
    - name: Compile
      run: clj -M -m cljs.main --optimizations advanced -c hello-world.core
