name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download & Install Clojure
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.11.1.1257.sh
        chmod +x linux-install-1.11.1.1257.sh
        sudo apt install -y rlwrap
        sudo ./linux-install-1.11.1.1257.sh

    - name: Compile
      run: clj -M -m cljs.main --optimizations advanced -c hello-world.core
